services:
  livekit:
    image: livekit/livekit-server
    restart: always
    network_mode: "host"
    volumes:
      - .:/app
      - /etc/ssl/certs/:/etc/ssl/certs/:ro
    command: --config "/app/livekit.yaml" --node-ip PUBLIC_IP
    healthcheck:
      test: wget --no-verbose --tries=5 --spider http://localhost:7880 || kill 1
      interval: 20s
      timeout: 1s
      retries: 5
  livekit-ingress:
    image: livekit/ingress
    restart: always
    network_mode: "host"
    volumes:
      - .:/app
    command: --config "/app/ingress.yaml"
    depends_on:
      livekit:
        condition: service_healthy
    healthcheck:
      test: wget --no-verbose --tries=5 --spider http://localhost:8088 || kill 1
      interval: 20s
      timeout: 1s
      retries: 5
  etherpad:
    image: mynaparrot/plugnmeet-etherpad
    restart: always
    network_mode: "host"
    volumes:
      - ./etherpad/APIKEY.txt:/opt/etherpad-lite/APIKEY.txt
      - ./etherpad/settings.json:/opt/etherpad-lite/settings.json
      - /usr/share/fonts/:/usr/share/fonts/:ro
      - /etc/fonts/:/etc/fonts/:ro
      - /usr/share/fontconfig/:/usr/share/fontconfig/:ro
      - /var/cache/fontconfig/:/var/cache/fontconfig/:ro
    healthcheck:
      test: curl -f --retry 5 --retry-delay 3 "http://localhost:9001/api" || kill 1
      interval: 20s
      timeout: 1s
      retries: 5
  plugnmeet:
    image: mynaparrot/plugnmeet-server
    restart: always
    network_mode: "host"
    volumes:
      - .:/app
      - /etc/ssl/certs/:/etc/ssl/certs/:ro
      - /usr/share/fonts/:/usr/share/fonts/:ro
      - /etc/fonts/:/etc/fonts/:ro
      - /usr/share/fontconfig/:/usr/share/fontconfig/:ro
      - /var/cache/fontconfig/:/var/cache/fontconfig/:ro
    command: --config "/app/config.yaml"
    depends_on:
      livekit:
        condition: service_healthy
    healthcheck:
      test: wget --no-verbose --tries=5 --spider http://localhost:8080 || kill 1
      interval: 20s
      timeout: 1s
      retries: 5
